### ISSUE TITLE
Integration problem of ODK Central with Google Data Studio

### ISSUE THREAD

**Issue by saadaan** [UDub-Impact/OData-Connector#24]
Hi,

I am getting following error from GDS during setup configuration:

```
Community Connector Error
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
You have entered an invalid URL.

Debug
ODK Central by UW Impact++

User has entered an invalid URL. API request to get table names failed. 
```

The URL is not invalid because it works fine with excel. Can you please help?

Thanks,
Saad

**Comment by wenjunsun** [comment]
Hello saadaan, what do you mean by "it works fine with excel"? Do you mean that you can pull your data into excel, but can't pull data into GDS? If you provide a little more detail of your workflow maybe I can help. The URL is supposed to be the URL to your ODK central database.

**Comment by saadaan** [comment]
Hi,

Yes, by excel working, I meant that I am able to successfully pull the data in Microsoft Excel, by providing the ODK central form URL in ODATA feed. But the same URL is not working on Google Data Studio, giving the error I mentioned above.

**Comment by wenjunsun** [comment]
Hello saadaan, sorry for the inconvenience that our app has caused. I currently don't know where exactly our code went wrong. If you can provide more information on how I can reproduce this error it would be great!
Also, our response time might be a little longer since summer is our club's off-season.
Since Google Data Studio has a built-in data connector to a CSV file, you can use that option for now to first pull data into a csv file and connect that file to GDS via CSV connector.
Again, thanks so much for your patience.

**Comment by saadaan** [comment]
Hi,

Can you send me some internal msg or email? I can share the URL and credentials with you. I am saad@saadaan.com

**Comment by wenjunsun** [comment]
Yep! Just sent you an internal email.
